# Spring MVC ????
# ?????????JSP????WEB-INF/jsp???
spring.mvc.view.prefix=/WEB-INF/jsp/
# ?????????JSP??????.jsp
spring.mvc.view.suffix=.jsp

# JSP??????
# ??JSP??????????????JSP??
server.servlet.jsp.init-parameters.development=true

# ???????
# ?????????8080
server.port=8080